FROM node:latest AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

#RUN npm run build

#FROM nginx:1.25.2-alpine-slim

# Copy the static file to my Nginx folder to serve static contain
#COPY --from=builder /app/build /usr/share/nginx/html

# Open the port to react
#EXPOSE 5173

# Run nginx in the foreground
#CMD ["nginx", "-g", "daemon off;"]